### PR TITLE
Install the attachment point.

### PR DESCRIPTION
**Pull request by juagargi**
Run in the attachment point itself. The script needs the files from the easy-rsa keys.

This repository might not be the best choice to put this script, but in the mean time I don't want it to get lost.
We can of course move it to another repo and close this PR.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-box/30)

### CODE REVIEW

**Comment by hausheer** [comment]
In my view the script which addresses issue #20 fits well here.

Could you also extend the README file (cf. issue #19) in this PR, to explain how this script is supposed to be run, and how to get the easy-rsa keys required for it, etc.?

**Comment by mlegner** [comment]
Thanks for this nice script, looks mostly good to me. I agree with @xabarass and @hausheer and also added some minor comments below.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[install_attachment_point.sh, line 45 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L60xpktePed76RD-8ZO:-L60xpktePed76RD-8ZP:b2ol4s) ([raw file](https://github.com/netsec-ethz/scion-box/blob/c396d9006ea6d4cfa3bdea3c76ad4e7975b6b43f/install_attachment_point.sh#L45)):*
> ```Shell
> 
> OPENVPNSERVERCONF=$(cat <<ENDOFCONF
> port 1194
> ```

We could have an optional commandline argument for the port (as this is also configurable on scion-coord).

---

*[install_attachment_point.sh, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L60xxYZCKOT2plIm5Pn:-L60xxYZCKOT2plIm5Po:b-h5kjv6) ([raw file](https://github.com/netsec-ethz/scion-box/blob/c396d9006ea6d4cfa3bdea3c76ad4e7975b6b43f/install_attachment_point.sh#L56)):*
> ```Shell
> 
> topology subnet
> server 10.0.8.0 255.255.255.0
> ```

Commandline argument for the subnet.

---

*[install_attachment_point.sh, line 58 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L60y4JPn50poJTyZVM1:-L60y4JQMjuBlycKHFZx:b-llkulc) ([raw file](https://github.com/netsec-ethz/scion-box/blob/c396d9006ea6d4cfa3bdea3c76ad4e7975b6b43f/install_attachment_point.sh#L58)):*
> ```Shell
> server 10.0.8.0 255.255.255.0
> ifconfig-pool-persist ipp.txt
> client-config-dir /home/scion/openvpn_ccd
> ```

We usually use `scion` as the username, but it would be nice if this also worked if we ever chose a different one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-:-L60xepg_EV8Hy_bFEhI:bh4nwkp)*

**Comment by mlegner** [comment]
Sorry, I mixed up two PRs, this should say "I agree with @hausheer" only. :)

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-:-L60yo4ZIqq8KGykMmEJ:b-ipifn9)*

**Comment by juagargi** [comment]
I'm going to extend the README in this PR

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[install_attachment_point.sh, line 45 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L60xpktePed76RD-8ZO:-L61MWPMZO1pN1xFmeVL:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-box/blob/c396d9006ea6d4cfa3bdea3c76ad4e7975b6b43f/install_attachment_point.sh#L45)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We could have an optional commandline argument for the port (as this is also configurable on scion-coord).
</blockquote></details>

Done.

---

*[install_attachment_point.sh, line 56 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L60xxYZCKOT2plIm5Pn:-L61NAJVcDLAQ8VnhTkU:br20uri) ([raw file](https://github.com/netsec-ethz/scion-box/blob/c396d9006ea6d4cfa3bdea3c76ad4e7975b6b43f/install_attachment_point.sh#L56)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Commandline argument for the subnet.
</blockquote></details>

Done. But when testing, I see that openvpn will complain because 10.0.8.0 will not go well with e.g. 255.0.0.0, so I added also an option for IP.

---

*[install_attachment_point.sh, line 58 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L60y4JPn50poJTyZVM1:-L61MV7Yogd25iF8vOmr:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-box/blob/c396d9006ea6d4cfa3bdea3c76ad4e7975b6b43f/install_attachment_point.sh#L58)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We usually use `scion` as the username, but it would be nice if this also worked if we ever chose a different one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-:-L6194Rb0el6tuSOgM62:b-byes6p)*

**Comment by mlegner** [comment]
Thanks for the changes. One more question: Is it intentional that some other setup steps (such as registering `update_gen.py` with cron or systemd) are not part of the script?

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-:-L61Ty5_4hwyPd4SVSiP:b-88rxm3)*

**Comment by hausheer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[README.md, line 7 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L61Za6ELAUQTzDkt5-9:-L61Za6ELAUQTzDkt5-A:bx6cstb) ([raw file](https://github.com/netsec-ethz/scion-box/blob/27ac0decaceb25e4ab9a4a68da8b15949282b9b2/README.md#L7)):*
> ```Markdown
> ## Install an Attachment Point
> To setup an Attachment Point (AP) we will need several files:
> - VPN related credential files. These files are usually generated where the Coordinator runs. Please check the instructions in the *README* of the *scion-coord* project.
> ```

I understand we need to setup a coordinator in order to get the required files to setup an attachment point. Then the coordinator would need to be informed again that this new attachment point now exists so that ASes can connect to it. So wouldn't it be better to directly let the coordinator do everything and then download everything from there, instead of having to manually copy the individual files? Ideally, there shouldn't be almost any manual steps involved at all, this should be all fully automated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30)*

**Comment by hausheer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 7 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L61Za6ELAUQTzDkt5-9:-L61aRkoy4jZxfrxvf1B:bcbcy7b) ([raw file](https://github.com/netsec-ethz/scion-box/blob/27ac0decaceb25e4ab9a4a68da8b15949282b9b2/README.md#L7)):*
<details><summary><i>Previously, hausheer (David Hausheer) wrote…</i></summary><blockquote>

I understand we need to setup a coordinator in order to get the required files to setup an attachment point. Then the coordinator would need to be informed again that this new attachment point now exists so that ASes can connect to it. So wouldn't it be better to directly let the coordinator do everything and then download everything from there, instead of having to manually copy the individual files? Ideally, there shouldn't be almost any manual steps involved at all, this should be all fully automated.
</blockquote></details>

I imaging that a user can select in the coordinator UI to have an AS setup as an attachment point (this requires that the AS has a public IP). We just need one additional check box for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30)*

**Comment by juagargi** [comment]
Since this script is to be used primarily in the infrastructure machines, I thought that we wanted to run the update gen manually and not every X minutes. Tell me if that's incorrect and I'll register the updater with a timer or in cron.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 7 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L61Za6ELAUQTzDkt5-9:-L62dJUghFALvKd9ix8x:bzg1crs) ([raw file](https://github.com/netsec-ethz/scion-box/blob/27ac0decaceb25e4ab9a4a68da8b15949282b9b2/README.md#L7)):*
<details><summary><i>Previously, hausheer (David Hausheer) wrote…</i></summary><blockquote>

I imaging that a user can select in the coordinator UI to have an AS setup as an attachment point (this requires that the AS has a public IP). We just need one additional check box for this.
</blockquote></details>

Completely agree. We could do this "user attachment point" in a second round, as we discussed. This script is intended only for the infrastructure nodes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-:-L62cao-uPVfuysmFzSk:b2qjd0o)*

**Comment by hausheer** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 7 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-L61Za6ELAUQTzDkt5-9:-L6Tgw6r2C5d0EU0RAcB:bdg01b7) ([raw file](https://github.com/netsec-ethz/scion-box/blob/27ac0decaceb25e4ab9a4a68da8b15949282b9b2/README.md#L7)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Completely agree. We could do this "user attachment point" in a second round, as we discussed. This script is intended only for the infrastructure nodes.
</blockquote></details>

You are right, I forgotten about the infrastructure nodes, as discussed. I added a comment in the related issue #20 . We can follow-up on this with a new PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30)*

**Comment by juagargi** [comment]
This PR will depend on PR #29 being merged beforehand. We need the arguments to call update gen with the right AS IA, account id, etc.

**Comment by juagargi** [comment]
If you guys give the LGTM, I'll merge this PR after #29 

---

Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/30#-:-L7dwd7kjqtQz70wh-Bw:b8jv78z)*

**Comment by hausheer** [comment]
Ok, I am going to test it again.

**Comment by juagargi** [comment]
I rebased the PR against the current master. Also picked only the commits that were not already merged to master, to ease the review.

---

Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-box/30#-:-L7j0qT01xWdXy9CPy7g:bperj5g)*

**Pull request merged**
