### PR TITLE
add command line arguments

### PR DESCRIPTION
**Pull request by juagargi**
Be able to call update gen with some parameters

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-box/29)

### CODE REVIEW

**Comment by hausheer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[update_gen.py, line 94 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5v9lBUGEIiT4cGySTt:-L5v9lBV3sysc37pyaR1:be309p4) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L94)):*
> ```Python
> #: API calls at the coordinator
> GET_REQ = SCION_COORD_URL + "api/as/getUpdatesForAP"
> POST_REQ = SCION_COORD_URL + "api/as/confirmUpdatesFromAP"
> ```

SCION_COORD_URL gets overwritten with https://coord.scionproto.net/ here, even if the url is set as a parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29)*

**Comment by mlegner** [comment]
@juagargi Made a pass and gave some minor comments below.

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[update_gen.py, line 61 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5wZ2DGZ5GQoiaL_otI:-L5wZ2DHW7iNB-VIixEn:bbxfkwa) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L61)):*
> ```Python
> 
> """
> The following configurations need to be customized to the AP
> ```

We could change this comment to say that options should be specified by commandline parameters. In fact, we do not need to have the empty definitions for `ACC_ID`, `ACC_PW`, `INTF_ADDR`, and `INTL_ADDR`.

---

*[update_gen.py, line 94 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5v9lBUGEIiT4cGySTt:-L5wYZLPgxUrSQB63e7S:b-awdzgy) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L94)):*
<details><summary><i>Previously, hausheer (David Hausheer) wrote…</i></summary><blockquote>

SCION_COORD_URL gets overwritten with https://coord.scionproto.net/ here, even if the url is set as a parameter.
</blockquote></details>

For me, there doesn't seem to be a problem. Initially, `SCION_COORD_URL` is set to https://coord.scionproto.net, however, it gets replaced by the commandline argument afterwards. Anyway, we may still want to replace this by https://scionlab.org.

---

*[update_gen.py, line 528 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5wZo8Ow8pes7E0weRO:-L5wZo8Ow8pes7E0weRP:b-gmq9g) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L528)):*
> ```Python
>     parser = argparse.ArgumentParser(description="Update the SCION gen directory")
>     parser.add_argument("--url", nargs="?", type=str,
>                         help="URL or the coordinator service")
> ```

"Coordination service" or "coordinator".

---

*[update_gen.py, line 534 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5wZsAfjwxNk4QCguLw:-L5wZsAfjwxNk4QCguLx:bp66vmm) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L534)):*
> ```Python
>                         help="The internal address")
>     parser.add_argument("--id", nargs="?", type=str,
>                         help="The SCION Coordinator user ID that has permission to access this AS")
> ```

This should be the *Account* ID.

---

*[update_gen.py, line 536 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5wZxLGod43V-cFh8xS:-L5wZxLGod43V-cFh8xT:bro2dka) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L536)):*
> ```Python
>                         help="The SCION Coordinator user ID that has permission to access this AS")
>     parser.add_argument("--secret", nargs="?", type=str,
>                         help="The secret for the SCION Coordinator user that has permission to access this AS")
> ```

Account here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-:-L5w_0R8PPxtMKNBppCs:bcwpq2)*

**Comment by hausheer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[update_gen.py, line 94 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5v9lBUGEIiT4cGySTt:-L5wepGLyJvXurxDrmOJ:bnu94xs) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L94)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

For me, there doesn't seem to be a problem. Initially, `SCION_COORD_URL` is set to https://coord.scionproto.net, however, it gets replaced by the commandline argument afterwards. Anyway, we may still want to replace this by https://scionlab.org.
</blockquote></details>

In my case, SCION_COORD_URL gets updated, but GET_REQ doesn't get updated, since it is set earlier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29)*

**Comment by juagargi** [comment]
I'm going to add another cmd argument to allow specifying the AS IA

---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[update_gen.py, line 61 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-box/29#-L5wZ2DGZ5GQoiaL_otI:-L5wuAZB7OFTNe8Y4ffK:b1eoui7) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L61)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

We could change this comment to say that options should be specified by commandline parameters. In fact, we do not need to have the empty definitions for `ACC_ID`, `ACC_PW`, `INTF_ADDR`, and `INTL_ADDR`.
</blockquote></details>

We can do that. This would force all the callers of update gen to pass the parameters, but I don't know how many places we have where we call update gen. If we can make the change now, tell me and I will do it in this PR (which makes total sense).

---

*[update_gen.py, line 94 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-box/29#-L5v9lBUGEIiT4cGySTt:-L5wuXvhC1L0VWJx01Ym:bvp5d4o) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L94)):*
<details><summary><i>Previously, hausheer (David Hausheer) wrote…</i></summary><blockquote>

In my case, SCION_COORD_URL gets updated, but GET_REQ doesn't get updated, since it is set earlier.
</blockquote></details>

Right, all derived variables from these elementary ones will have to be altered as well. I'm changing that right now.

---

*[update_gen.py, line 528 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-box/29#-L5wZo8Ow8pes7E0weRO:-L5wvGpJ73R_725T_goN:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L528)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

"Coordination service" or "coordinator".
</blockquote></details>

Done.

---

*[update_gen.py, line 534 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-box/29#-L5wZsAfjwxNk4QCguLw:-L5wwp2M0-jJi_u4aYvd:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L534)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

This should be the *Account* ID.
</blockquote></details>

Done.

---

*[update_gen.py, line 536 at r2](https://beta.reviewable.io/reviews/netsec-ethz/scion-box/29#-L5wZxLGod43V-cFh8xS:-L5wx0wt-4wS5poguUZU:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L536)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

Account here as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-box/29#-:-L5xA3of2L_jzHJAv9oI:btm0l6k)*

**Comment by mlegner** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[update_gen.py, line 61 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5wZ2DGZ5GQoiaL_otI:-L5xH7Vojr-irbHdoiZv:b1dan3x) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L61)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

We can do that. This would force all the callers of update gen to pass the parameters, but I don't know how many places we have where we call update gen. If we can make the change now, tell me and I will do it in this PR (which makes total sense).
</blockquote></details>

The users will have to specify these anyway, as empty values are not legal. Therefore I suggest already removing them now and making the arguments mandatory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29)*

**Comment by hausheer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[update_gen.py, line 94 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5v9lBUGEIiT4cGySTt:-L5zMhxJ6BzzOcWAAU5H:b215729) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L94)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Right, all derived variables from these elementary ones will have to be altered as well. I'm changing that right now.
</blockquote></details>

This works for me now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29)*

**Comment by hausheer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[update_gen.py, line 61 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5wZ2DGZ5GQoiaL_otI:-L5zNdgyjDR_Jxhd0EIA:b-i6hexf) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L61)):*
<details><summary><i>Previously, mlegner (Markus Legner) wrote…</i></summary><blockquote>

The users will have to specify these anyway, as empty values are not legal. Therefore I suggest already removing them now and making the arguments mandatory.
</blockquote></details>

Yes it should not be allowed to leave these empty, the user should at least be warned if it is the case, similar to INTF_ADDR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29)*

**Comment by hausheer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[update_gen.py, line 213 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5ziWkFK_CDorvjeCD8:-L5ziWkGlEKp7Jy7TugO:byatdnq) ([raw file](https://github.com/netsec-ethz/scion-box/blob/7f7044301771c2b72c10f0722d9358387067f460/update_gen.py#L213)):*
> ```Python
>             return None, e
>         content = resp.content.decode('utf-8')
>         resp_dict = json.loads(content)
> ```

There is an uncatched `JSONDecodeError("Expecting value", s, err.value)`error here when the AS is *not* existing on the coordinator. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29)*

**Comment by juagargi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[update_gen.py, line 61 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5wZ2DGZ5GQoiaL_otI:-L617wXJ_DvalvtD1qwD:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L61)):*
<details><summary><i>Previously, hausheer (David Hausheer) wrote…</i></summary><blockquote>

Yes it should not be allowed to leave these empty, the user should at least be warned if it is the case, similar to INTF_ADDR
</blockquote></details>

Done.

---

*[update_gen.py, line 213 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5ziWkFK_CDorvjeCD8:-L6189I5sF9ocsjeZqrL:b472pgp) ([raw file](https://github.com/netsec-ethz/scion-box/blob/7f7044301771c2b72c10f0722d9358387067f460/update_gen.py#L213)):*
<details><summary><i>Previously, hausheer (David Hausheer) wrote…</i></summary><blockquote>

There is an uncatched `JSONDecodeError("Expecting value", s, err.value)`error here when the AS is *not* existing on the coordinator. 
</blockquote></details>

That seems to be addressed in issue #168 with PR #169 (in coordinator)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29)*

**Comment by hausheer** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[update_gen.py, line 61 at r2](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5wZ2DGZ5GQoiaL_otI:-L61f1UqJMPfnsRdNl2W:bb6ywmx) ([raw file](https://github.com/netsec-ethz/scion-box/blob/520ffa8d10603dc2c911d394edf0dbc8b7ef59e9/update_gen.py#L61)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

LGTM

---

*[update_gen.py, line 213 at r3](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29#-L5ziWkFK_CDorvjeCD8:-L61cfGKr78SyGohhdQ0:b-ytfsdj) ([raw file](https://github.com/netsec-ethz/scion-box/blob/7f7044301771c2b72c10f0722d9358387067f460/update_gen.py#L213)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

That seems to be addressed in issue #168 with PR #169 (in coordinator)
</blockquote></details>

Not quite, PR #169 only addresses the scion-coord part of it. But when update_gen.py is provided with a AS that doesn't exist in the coordinator, it will result in this JSON error, which should be catched (the result from the coordinator should be checked before decoding it and the user should be informed that the AS doesn't exist)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-box/29)*

**Comment by juagargi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[update_gen.py, line 213 at r3](https://beta.reviewable.io/reviews/netsec-ethz/scion-box/29#-L5ziWkFK_CDorvjeCD8:-L6GaNX8ANPfh1G7mxq2:b-xtadf9) ([raw file](https://github.com/netsec-ethz/scion-box/blob/7f7044301771c2b72c10f0722d9358387067f460/update_gen.py#L213)):*
<details><summary><i>Previously, hausheer (David Hausheer) wrote…</i></summary><blockquote>

Not quite, PR #169 only addresses the scion-coord part of it. But when update_gen.py is provided with a AS that doesn't exist in the coordinator, it will result in this JSON error, which should be catched (the result from the coordinator should be checked before decoding it and the user should be informed that the AS doesn't exist)
</blockquote></details>

Completely right, fixing it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/netsec-ethz/scion-box/29)*

**Pull request merged**
